### PR TITLE
New Logo Favicon

### PR DESCRIPTION
**Pull request by Stephan905**

### CODE REVIEW

**Comment by lowpolyneko** [comment]
what are you intending on replacing for the website? i can't really tell because the content is arbitrarily named.

**Comment by Stephan905** [comment]
the favicon (little icon next to browser tab) I deleted the old files and replaced them with the new ones. the old one had some random penguin

**Comment by lowpolyneko** [comment]
the favicon needs to be an `.ico` file with the `.png` backup. also, its limited to 16x16 pixels. see https://developer.mozilla.org/en-US/docs/Glossary/Favicon. to save some work, it'll also make it easier if you rename the files to `favicon.ico` and `favicon.png` respectively so you wouldn't have to edit the template html file. otherwise that would have to be edited to match.

**Comment by lowpolyneko** [comment]
stale

**Pull request closed without merging**
