### PR TITLE
Created & Edited Tutorial for Connecting to UIC WiFi

### PR DESCRIPTION
**Pull request by xmasscan**
Created a barebones tutorial article on how to connect to UIC's WiFi on Linux.
All of my information is sourced from the following UIC article on connecting to it via Android:
https://help.uillinois.edu/TDClient/37/uic/KB/ArticleDet?ID=915

### CODE REVIEW

**Comment by SohamG** [comment]
Looks good. Would be epic to have a GNOME screenshot too since thats (unfortunately) the default DE in a lot of places.

**Comment by SohamG** [comment]
If you could rename your markdown file to something simple like just `wifi.md` that would make the final URL be `lug.cs.uic.edu/wifi`. Right now the article would be at the URL `lug.cs.uic.edu/UIC-WiFi` which is harder to remember/type/spread

**Comment by xmasscan** [comment]
Didn't see these until now - will definitely rename the markdown file, will hopefully get the GNOME desktop screenshot by this weekend.

**Comment by lowpolyneko** [comment]
woah tysm for making this article! i've been wanting it since the start of the semester lol

just fyi, when you renamed the markdown file you actually duplicated it on accident, once you remove it and add your other screenshot it looks good to merge :D

**Comment by xmasscan** [comment]
Finally added the GNOME desktop screenshot alongside the KDE screenshot (very swiftly, I know)

Also, thank you for pointing out that I copied the markdown file instead of just renaming it, removed the original markdown file, leaving only wifi.md :)

**Comment by lowpolyneko** [comment]
lgtm! thank you so much :D

**Pull request merged**
